import Link from "next/link";
import { requireUser } from "@/lib/access";
import { db } from "@/lib/db";
import { createProject } from "@/app/actions";

const field = "mt-2 w-full rounded-xl border border-white/10 bg-[#0a101a] px-4 py-3 outline-none focus:border-orange-400";
export default async function Projects() {
  const userId = await requireUser();
  const projects = await db.project.findMany({ where: { workspace: { members: { some: { userId } } } }, orderBy: { createdAt: "desc" }, include: { goals: { orderBy: { createdAt: "desc" }, take: 1 } } });
  return <div className="mx-auto max-w-5xl"><p className="text-xs font-bold uppercase tracking-[.25em] text-orange-400">Portfolio</p><h1 className="mt-3 text-4xl font-bold">Projects</h1><p className="mt-3 text-slate-400">Start with a clear goal. Forge will organize the work.</p><div className="mt-10 grid gap-8 lg:grid-cols-[1fr_1.1fr]"><form action={createProject} className="h-fit rounded-2xl border border-white/10 bg-[#111824] p-7"><h2 className="text-xl font-semibold">Create a project</h2><label className="mt-6 block text-sm text-slate-300">Project name<input required minLength={2} maxLength={80} name="name" placeholder="e.g. Atlas AI" className={field}/></label><label className="mt-5 block text-sm text-slate-300">Description<textarea name="description" maxLength={2000} rows={3} placeholder="What are you building?" className={field}/></label><label className="mt-5 block text-sm text-slate-300">Business goal<textarea required minLength={10} maxLength={2000} name="goal" rows={4} placeholder="Build an AI SaaS that can reach €5,000 MRR" className={field}/></label><button className="mt-6 rounded-xl bg-orange-400 px-5 py-3 font-semibold text-slate-950 hover:bg-orange-300">Create project →</button></form><div><h2 className="text-xl font-semibold">All projects</h2><div className="mt-5 space-y-3">{projects.map(project => <Link key={project.id} href={`/dashboard/projects/${project.id}`} className="block rounded-2xl border border-white/10 bg-[#111824] p-5 hover:border-orange-400/50"><p className="font-semibold">{project.name} <span className="float-right text-orange-400">↗</span></p><p className="mt-2 line-clamp-2 text-sm text-slate-400">{project.goals[0]?.statement}</p></Link>)}{projects.length===0 && <div className="rounded-2xl border border-dashed border-white/15 p-8 text-sm text-slate-500">Your projects will appear here.</div>}</div></div></div></div>;
}
