import { requireProject } from "@/lib/access";
import { db } from "@/lib/db";
import { researchProviderConfigured } from "@/lib/research/provider";

export default async function Research({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  await requireProject(id);
  const sessions = await db.researchSession.findMany({ where: { projectId: id }, orderBy: { startedAt: "desc" }, take: 10, include: { sources: true, findings: { include: { source: true } } } });
  const configured = researchProviderConfigured(process.env) && Boolean(process.env.OPENAI_API_KEY?.trim()) && process.env.DEMO_MODE !== "true";
  return <section className="space-y-5"><div><h2 className="text-2xl font-semibold">Research evidence</h2><p className="mt-2 text-sm text-slate-400">Retrieved public pages and exact source quotes. Findings are AI interpretations, not independently verified market facts.</p></div>
    {!configured && <p className="rounded-xl border border-amber-400/30 bg-amber-400/5 p-4 text-sm text-amber-100">{process.env.DEMO_MODE === "true" ? "MOCKED demo mode: research outlines contain no live sources." : "NOT CONFIGURED: live research requires a configured search provider and OPENAI_API_KEY on the server. Use RESEARCH_PROVIDER=searxng with RESEARCH_SEARXNG_BASE_URL or BRAVE_SEARCH_API_KEY."}</p>}
    {configured && <p className="rounded-xl border border-emerald-400/20 bg-emerald-400/5 p-4 text-sm text-emerald-100">CONFIGURED: a search provider and AI credentials are present. A session is VERIFIED only after pages are retrieved and its source quotes pass validation.</p>}
    {sessions.map(session => <article key={session.id} className="rounded-2xl border border-white/10 bg-[#111824] p-6"><div className="flex flex-wrap justify-between gap-3"><h3 className="font-semibold">Research session · {session.startedAt.toLocaleString()}</h3><span className="text-xs text-orange-300">{session.status === "COMPLETED" ? "VERIFIED retrieval" : "ERROR"} · {session.provider}</span></div>{session.summary && <p className="mt-3 text-sm text-slate-300">{session.summary}</p>}{session.status === "COMPLETED" && <><p className="mt-3 text-xs text-slate-500">{session.queryCount} searches · {session.sources.length} retrieved pages. Quotes were checked against saved excerpts.</p><div className="mt-5 space-y-4">{session.findings.map(finding => <div key={finding.id} className="rounded-xl border border-white/10 p-4"><p className="text-xs font-bold uppercase tracking-widest text-orange-300">{finding.area.replaceAll("_", " ")} · {finding.confidence.toLowerCase()} confidence</p><p className="mt-2 text-sm text-slate-200">{finding.claim}</p><blockquote className="mt-3 border-l-2 border-orange-400/50 pl-3 text-sm text-slate-400">“{finding.quote}”</blockquote><p className="mt-2 text-xs text-slate-500">Limitation: {finding.limitation}</p><a className="mt-2 inline-block break-all text-xs text-orange-300 underline" href={finding.source.url} target="_blank" rel="noopener noreferrer">{finding.source.title} · retrieved {finding.source.retrievedAt.toLocaleString()}</a></div>)}</div><details className="mt-5 text-sm text-slate-400"><summary className="cursor-pointer">Inspect all {session.sources.length} source pages</summary><ul className="mt-3 space-y-3">{session.sources.map(source => <li key={source.id} className="break-all"><a className="text-orange-300 underline" href={source.url} target="_blank" rel="noopener noreferrer">{source.title}</a><p className="text-xs text-slate-500">Query: {source.query} · retrieved {source.retrievedAt.toLocaleString()}</p><details className="mt-1 text-xs"><summary className="cursor-pointer">Saved excerpt</summary><p className="mt-1 whitespace-pre-wrap break-words">{source.excerpt}</p></details></li>)}</ul></details><p className="mt-4 text-xs text-slate-500">Limitations: {session.limitations}</p></>}</article>)}
    {sessions.length === 0 && <p className="rounded-2xl border border-dashed border-white/15 p-8 text-sm text-slate-500">No live research sessions yet. Start the project workflow after configuring the research provider.</p>}
  </section>;
}
