import Link from "next/link";
import { requireUser } from "@/lib/access";
import { db } from "@/lib/db";

export default async function Dashboard() {
  const userId = await requireUser();
  const projects = await db.project.findMany({ where: { workspace: { members: { some: { userId } } } }, include: { goals: { orderBy: { createdAt: "desc" }, take: 1 }, _count: { select: { tasks: true, reports: true, runs: true } } }, orderBy: { updatedAt: "desc" } });
  return <div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[.25em] text-orange-400">Workspace overview</p><h1 className="mt-3 text-4xl font-bold">Your command center</h1><p className="mt-3 text-slate-400">Turn business goals into coordinated work.</p></div><Link href="/dashboard/projects" className="rounded-xl bg-orange-400 px-5 py-3 font-semibold text-slate-950">New project →</Link></div><div className="mt-10 grid gap-4 sm:grid-cols-3">{[["Projects",projects.length],["Agent runs",projects.reduce((n,p)=>n+p._count.runs,0)],["Reports",projects.reduce((n,p)=>n+p._count.reports,0)]].map(([label,value])=><div key={label} className="rounded-2xl border border-white/10 bg-[#111824] p-6"><p className="text-sm text-slate-500">{label}</p><p className="mt-3 text-3xl font-bold">{value}</p></div>)}</div><h2 className="mt-12 text-xl font-semibold">Recent projects</h2><div className="mt-5 grid gap-4 md:grid-cols-2">{projects.map(project => <Link key={project.id} href={`/dashboard/projects/${project.id}`} className="rounded-2xl border border-white/10 bg-[#111824] p-6 transition hover:border-orange-400/50"><p className="text-lg font-semibold">{project.name} <span className="float-right text-orange-400">↗</span></p><p className="mt-2 line-clamp-2 text-sm text-slate-400">{project.goals[0]?.statement}</p><p className="mt-6 text-xs text-slate-500">{project._count.tasks} tasks · {project._count.reports} reports</p></Link>)}</div>{projects.length===0 && <div className="mt-5 rounded-2xl border border-dashed border-white/15 p-12 text-center text-slate-400">No projects yet. Create your first business goal to start.</div>}</div>;
}
